# Site Settings
# Edit this file in Git.
name: "ml-move"
mark: "ML"
description: "A fast, modern site — multilanguage-ready."
url: "https://ml-move.pages.dev"
defaultLocale: en
analyticsProvider: none
gtmId: ""
umamiUrl: ""
umamiId: ""
mapLatitude: "-7.4941954"
mapLongitude: "110.8065028"
orgName: ""
orgEmail: ""
socialLinks: []
